project_string/users/forms.py
from flask import Flask
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError


class RegistrationForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired(), Length(min = 6, max = 20)])
    confirm_password = PasswordField('Confirm-Password', validators = [DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')



class LoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit = SubmitField('Login')



class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired(), Length(min = 5, max=15)])
    email = StringField('Email', validators = [DataRequired(), Email()])
    profile_image = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
    submit = SubmitField('Update')


class RequestResetForm(FlaskForm):
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

  

project_string/__init__.py
from flask import Flask
from project_string.config import firebase
import os

def create_app(config_class = firebase):
    app = Flask(__name__)
    app.config.from_object(firebase)
    app.config['SECRET_KEY'] = os.environ.get('SECRET_KEY')
#     app.config.update(dict(
#     SECRET_KEY = os.environ.get('SECRET_KEY'),
#     WTF_CSRF_SECRET_KEY = os.environ.get('WTF_CSRF_SECRET_KEY')
# ))
    #csrf.init_app(app)

    from project_string.users.routes import users
    from project_string.main.routes import main
    from project_string.errors.error_handlers import errors
    
    app.register_blueprint(users)
    app.register_blueprint(main)
    app.register_blueprint(errors)

    return app

project_string/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    return render_template('home.html', title="Welcome")


@main.route("/about")
def about():
    return render_template('about.html', title='About')

project_string/users/routes.py
from flask import Blueprint, render_template, url_for, flash, redirect, request, session
from flask_login import login_user, current_user, logout_user, login_required
from project_string.users.forms import RegistrationForm, LoginForm, RequestResetForm, UpdateAccountForm
from project_string.config import firebase
from firebase_admin import auth

users = Blueprint('users', __name__)

@users.route("/register", methods = ['GET', 'POST'])
def register():
    try:
        if session['usr']:
            return redirect(url_for('main.home'))
    except:
        form = RegistrationForm()
        if form.validate_on_submit():
            # user = firebase.auth().create_user_with_email_and_password(form.email.data, form.password.data)
            # firebase.auth().send_email_verification(user['idToken'])
            # flash(f'An email is send to your email-id to verfisy your account', 'success')
            # return redirect(url_for('users.register'))
            
            try:
                user = firebase.auth().create_user_with_email_and_password(form.email.data, form.password.data)
                firebase.auth().send_email_verification(user['idToken'])
                flash(f'An email is send to your email-id to verfisy your account', 'success')
                return redirect(url_for('users.register'))
            except:
                flash(f'Email is already is in use.', 'danger')
                return redirect(url_for('users.register')) 
            
    return render_template('register.html', title = "Register", form = form)



@users.route("/login", methods = ['GET', 'POST'])
def login():
    try:
        if session['usr']:
            return redirect(url_for('main.home'))
    except:
        form = LoginForm()
        if form.validate_on_submit():
            try:
                user = firebase.auth().sign_in_with_email_and_password(form.email.data, form.password.data)
                user_info = firebase.auth().get_account_info(user['idToken'])
                firebase.auth().send_email_verification(user['idToken'])
                if user_info['users'][0]['emailVerified'] == False:
                    flash(f'You have not verified your mail yet.', 'danger')
                    firebase.auth().send_email_verification(user['idToken'])
                    flash(f'An email is send to your email-id to verfisy your account', 'success')
                    return redirect(url_for('users.login'))
                else:
                    session['usr'] = user
                    session['email'] = form.email.data
                
                next_page = request.args.get('next')       
                #print("the current user id ", firebase.auth().current_user['loaclId'])     
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            except:
                flash('Invalid credentials.', 'danger')   
    return render_template('login.html', title = "Login", form = form)




@users.route("/account", methods = ['GET', 'POST'])
def account():
    form = UpdateAccountForm()
    return render_template('account.html', title = 'Account', form = form)



@users.route("/logout")
def logout():
    firebase.auth().current_user = None
    session.clear()
    return redirect(url_for('main.home'))


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        try:
            firebase.auth().send_password_reset_email(form.email.data)
            flash(f'An email has been sent to your email-id to reset your password', 'success')
            return redirect(url_for('users.reset_request'))
        except:
            flash(f'Email not found', 'danger')
            return redirect(url_for('users.forgot_password'))
    return render_template('reset_request.html', title='Reset Password', form=form)

project_string/templates/about.html
{% extends "base.html" %}
{% block topblock %}
<div class="style-backgroud_images">
    <div class="container padding-style">
        <div class="media paddings">
            <img class="about_image" class="img-fluid img-resposive" src="{{ url_for('static', filename = 'assets/carousel_slide/about.jpg') }}">
            <div class="media-body">
                <h3>Melody is the essence of music. I compare a good melodist to a fine racer, and counterpointists to hack post-horses; therefore be advised, let well alone and remember the old Italian proverb: Chi sa più, meno sa—Who knows most, knows least.</h3>
                <h5>--- Wolfgang Amadeus Mozart</h5>
            </div>
        </div>
        <div class="container" style="padding-top: 10%;">
            <h4>Project-String is a initiative to provide music lessons in a easy and effective way. We are tryig to provide the violin lessions with proved and tested practice methods.</h4>
            <br/>
            <br/>

            <h3>The violin is my mistress, but the guitar is my master.</h3>
            <h5>---Nicolo Paginini</h5>
            
        </div>
    </div>
</div>
{% endblock %}

project_string/templates/account.html
{% extends "base.html" %}
{% block topblock %}
<div class="style-backgroud_images">
    <div class="container padding-style">
        <div class="media paddings">
            <img class="rounded-circle account-image" src=" {{ url_for('static', filename = 'assets/profile_images/default.jpg') }}">
            <div class="media-body">
                <h2 class="account-heading">{{ session['email'] }}</h2>
                <p>{{ session['email'] }}</p>

                <br/><br/>
                <h3>User Description</h3>
                <br/>
                <h6>Email Verification: -</h6>
                <h6>Last Active: - </h6>
                <h6>Joined: - </h6>
                <h6>Uploads: - </h6>
                <h6>Favourites: - </h6>
                <h6>Subsribes: - </h6>
                <h6>Profile Views: - </h6>
                <h6>Profile Comments: - </h6>
                <h6>Forum Posts: - </h6>
                <div class="container">
                    
                        <form method="POST" action="" enctype = "multipart/form-data">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <legend class="border-bottom md-4">Update Account</legend>
                                    {% with messages = get_flashed_messages(with_categories=true) %}
                                        {% if messages %}
                                            {% for category, message in messages %}
                                                <div class="alert alert-{{ category }}">
                                                    {{ message }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    {% endwith %}
                                <div class="background_content">
                                    <div class="form-group form-input-field">
                                        {{ form.username.label(class="form-control-label") }}
                
                                        {% if form.username.errors %}
                                            {{ form.username(class="form-control is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.username.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.username(class="form-control") }}
                                        {% endif %}
                                    </div>
                
                                    <div class="form-group form-input-field">
                                        {{ form.email.label(class="form-control-label") }}
                                    
                                        {% if form.email.errors %}
                                            {{ form.email(class="form-control is-invalid") }}
                                            <div class="invalid-feedback">
                                                {% for error in form.email.errors %}
                                                    <span>{{ error }}</span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.email(class="form-control") }}
                                        {% endif %}
                                    </div>

                                    <div class="form-group form-input-field">
                                        {{ form.profile_image.label() }}
                                        {{ form.profile_image(class="form-control-file") }}
                                        {% if form.profile_image.errors %}
                                            {% for error in form.profile_image.errors %}
                                                <span class="text-danger">{{ error }}</span></br>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </fieldset>
                            
                            <div class="form-group">
                                {{ form.submit(class="btn btn-outline") }}
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project_string/templates/base.html
<!DOCTYPE html>
<html>

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
  <!--
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='footer.css') }}">
    -->
  {% if title %}
  <title>ProjectString - {{ title }}</title>
  {% else %}
  <title>ProjectString</title>
  {% endif %}
</head>

<body>
  <header class="myNavbar" style="color: azure;">
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: rgba(0, 0, 0, 0.7); padding: 1rem;">
      <div class="container">
        <a class="navbar-brand font-weight-bold" style="font-size: 30px;" href="/">Project-String</a>
        <button aria-controls="navbarControls" aria-expanded="false" aria-label="Toggle navigation"
          class="navbar-toggler" data-target="#navbarControls" data-toggle="collapse" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarControls">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
            </li>
            {% if session["usr"] %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">{{ session["email"] }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">Register</a>
              </li>
            {% endif %}   
          </ul>
        </div>
      </div>
    </nav>
  </header>
  {% block topblock %}{% endblock %}
  <main role="main" class="container">  
    {% block main %}{% endblock %}
  </main>

  <footer>
    <footer class="bg-dark text-white text-center text-lg-start">
      <div class="container p-4">
        <div class="row">
          <div class="col-lg-6 col-md-12 mb-4 mb-md-0">
            <h5 class="text-uppercase">Footer Content</h5>

            <p>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste atque ea quis
              molestias. Fugiat pariatur maxime quis culpa corporis vitae repudiandae aliquam
              voluptatem veniam, est atque cumque eum delectus sint!
            </p>
          </div>

          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase">Links</h5>

            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
 
          <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
            <h5 class="text-uppercase mb-0">Links</h5>

            <ul class="list-unstyled">
              <li>
                <a href="#!" class="text-white">Link 1</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 2</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 3</a>
              </li>
              <li>
                <a href="#!" class="text-white">Link 4</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </div>
      <!-- Grid container -->
      <div class="container">
        <div class="col-offset-md-3 col-auto mb-4 mb-md-0">
          <div class="form-outline mb-4">
            <input type="email" id="form5Example2" class="form-control" />
            <label class="form-label" for="form5Example2">Email address</label>
          </div>
        </div>
        <div class="col-auto mb-4 mb-md-0">
          <button type="submit" class="btn btn-primary mb-4">Subscribe</button>
        </div>
      </div>

      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
        © 2020 Copyright:
        <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
      </div>
      <!-- Copyright -->
    </footer>
  </footer>


  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

project_string/templates/home.html
{% extends "base.html" %}
{% block topblock %}
  <div class="carousel slide" data-ride="carousel" id="carouselIndicator">
    <ol class="carousel-indicators">
      <li class="active" data-slide-to="0" data-target="#carouselIndicator"></li>
      <li data-slide-to="1" data-target="#carouselIndicator"></li>
      <li data-slide-to="2" data-target="#carouselIndicator"></li>
      <li data-slide-to="3" data-target="#carouselIndicator"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img alt="First slide" class="d-block w-100" src="{{ url_for('static', filename='assets/carousel_slide/01.jpg') }}">
        <div class="carousel-caption  d-md-block d-sm-block d-xs-block">
          <h5 class="animated bounceInRight" style="animation-delay: 1s">Learn Easy & Proper</h5>
          <p class="animated bounceInLeft" style="animation-delay: 2s">Learn with the proven practice routine with our best teachers.</p>
          <p class="animated bounceInRight" style="animation-delay: 3s"><a href="#">More Info</a></p>
        </div>
      </div>
      <div class="carousel-item">
        <img alt="Second slide" class="d-block w-100" src="{{ url_for('static', filename='assets/carousel_slide/02.jpg') }}">
        <div class="carousel-caption  d-md-block d-sm-block d-xs-block">
          <h5 class="animated slideInDown" style="animation-delay: 1s">Learn Live</h5>
          <p class="animated fadeInUp" style="animation-delay: 2s">There is live sessions to learn. Also private and public sessions are Available.</p>
          <p class="animated zoomIn" style="animation-delay: 3s"><a href="#">More Info</a></p>
        </div>
      </div>
      <div class="carousel-item">
        <img alt="Third slide" class="d-block w-100" src="{{ url_for('static', filename='assets/carousel_slide/03.jpg') }}">
        <div class="carousel-caption  d-md-block d-sm-block d-xs-block">
          <h5 class="animated zoomIn" style="animation-delay: 1s">Free Videos</h5>
          <p class="animated fadeInLeft" style="animation-delay: 2s">Learn with free free video lessions. (for non premium members)</p>
          <p class="animated zoomIn" style="animation-delay: 3s"><a href="#">Learn Now</a></p>
        </div>
      </div>
      <div class="carousel-item">
        <img alt="Third slide" class="d-block w-100" src="{{ url_for('static', filename='assets/carousel_slide/04.jpg') }}">
        <div class="carousel-caption  d-md-block d-sm-block d-xs-block">
          <h5 class="animated zoomIn" style="animation-delay: 1s">Premuim Membership</h5>
          <p class="animated fadeInLeft" style="animation-delay: 2s">Become a part of aur family. Learn directly with our musicians.</p>
          <p class="animated zoomIn" style="animation-delay: 3s"><a href="#">Register</a></p>
        </div>
      </div>
    </div><a class="carousel-control-prev" data-slide="prev" href="#carouselIndicator" role="button"><span aria-hidden="true" class="carousel-control-prev-icon"></span> <span class="sr-only">Previous</span></a> <a class="carousel-control-next" data-slide="next" href="#carouselIndicator" role="button"><span aria-hidden="true" class="carousel-control-next-icon"></span> <span class="sr-only">Next</span></a>
  </div>
{% endblock %}

{% block main %}
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{ url_for('static', filename='assets/project_images/01.jpg') }}" style="border-radius: 15px 50px;" class="img-fluid">
          <div class="card-body">
            <h5 class="card-title">Are you playing in tune?</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-dark">More Info</a>
          </div>
        </div>   
      </div>

      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{ url_for('static', filename='assets/project_images/02.jpg') }}" style="border-radius: 15px 50px;" class="img-fluid">
          <div class="card-body">
            <h5 class="card-title">Are you having right bow hold?</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-dark">More Info</a>
          </div>
        </div>   
      </div>

      <div class="col-sm-4">
        <div class="card" style="width: 18rem;">
          <img class="card-img-top" src="{{ url_for('static', filename='assets/project_images/03.jpg') }}" style="border-radius: 15px 50px;" class="img-fluid">
          <div class="card-body">
            <h5 class="card-title">Trouble with playing Pagini?</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            <a href="#" class="btn btn-dark">More Info</a>
          </div>
        </div>   
      </div>
    </div>
  </div>

{% endblock %}

project_string/templates/login.html
{% extends "base.html" %}
{% block topblock %}
<div class="backgroud_images">
    <div class="container padding-style">
        <center>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom md-4">Login</legend>
                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category, message in messages %}
                                    <div class="alert alert-{{ category }}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    <div class="background_content">
                        <div class="form-group form-input-field">
                            {{ form.email.label(class="form-control-label") }}
    
                            {% if form.email.errors %}
                                {{ form.email(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control") }}
                            {% endif %}
                        </div>
    
                        <div class="form-group form-input-field">
                            {{ form.password.label(class="form-control-label") }}
                        
                            {% if form.password.errors %}
                                {{ form.password(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                </fieldset>
                
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline") }}
                </div>
                <small>
                    <a  class="text-light" href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </form>
            <div class="border-top pt-3">
                <small class="text-dark">
                    Don't have an account? <a class="text-light" href="{{ url_for('users.register') }}">Sign Up</a>
                </small>
            </div>
        </center>
        
    </div>
</div>
{% endblock %}

project_string/templates/register.html
{% extends "base.html" %}
{% block topblock %}
<div class="backgroud_images">
    <div class="container padding-style">
        <center>
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom md-4">Register Now</legend>

                        {% with messages = get_flashed_messages(with_categories=true) %}
                            {% if messages %}
                                {% for category, message in messages %}
                                    <div class="alert alert-{{ category }}">
                                        {{ message }}
                                    </div>
                                {% endfor %}
                            {% endif %}
                        {% endwith %}
                    <div class="background_content">

                        <div class="form-group form-input-field">
                            {{ form.email.label(class="form-control-label") }}
    
                            {% if form.email.errors %}
                                {{ form.email(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class="form-control") }}
                            {% endif %}
                        </div>
    
                        <div class="form-group form-input-field">
                            {{ form.password.label(class="form-control-label") }}
                        
                            {% if form.password.errors %}
                                {{ form.password(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password(class="form-control") }}
                            {% endif %}
                        </div>
    
                        <div class="form-group form-input-field">
                            {{ form.confirm_password.label(class="form-control-label") }}
                        
                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password(class="form-control is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.confirm_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class="form-control") }}
                            {% endif %}
                        </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline") }}
                </div>
            </form>
            <div class="border-top pt-3">
                <small class="text-dark">
                    Already Have An Account? <a class="text-light" href="{{ url_for('users.login') }}">Sign In</a>
                </small>
            </div>
        </center>
        
    </div>
</div>
{% endblock %}